### ISSUE TITLE
License for refl1d

### ISSUE THREAD

**Issue by MridulS** [reflectometry/refl1d#212]
Hi! I am trying to package up refl1d for conda-forge (https://github.com/conda-forge/staged-recipes/pull/27983), so refl1d is available not just on pip but users can also do `conda/mamba install refl1d` too :)

I'm a bit confused about the license that I should point towards, in the root of the repo the `License.txt` says it's in the public domain, but there is also https://refl1d.readthedocs.io/en/latest/getting_started/license.html which states it has code that is licensed BSD and GPL.

**Comment by bmaranville** [comment]
We just made the license statement consistent within the project, so the same license is shown in the documentation and the `LICENSE.txt` file (the documentation pulls the license from that file).
We are using the 3-clause BSD license.
