### ISSUE TITLE
Mixtures

### ISSUE THREAD

**Issue by mettingc** [reflectometry/refl1d#31]
Tried to create a mixture but an error is returned which says that the object has no base. Pretty sure I gave it one though. This is either a documentation issue or a bug.

**Comment by cara-401** [comment]
Using the code below, among the available methods for mixlayer I have to_dict(). However, when fitting, this error keeps occurring: "AttributeError: 'list' object has no attribute 'to_dict'". 

from refl1d.names import *

SiO2 = Material('SiO2', density=2.65)
PMMA = Material('C5O2H8', density=1.18)
mixlayer = Mixture.bymass(Al2O3, PMMA, 30)
sample = silicon(0,5) | SiO2(16,5) | PMMA (900,5) | mixlayer(23,5) | air

sample[1].thickness.pm(5)
sample[2].thickness.pm(50)
sample[3].thickness.pm(10)

file = 'datafile.txt'
probe = load4(file, back_reflectivity = False, L = 7.64391, dT = 0.0005, radiation = 'xray', columns = 'Q R dR dQ')

M = Experiment(probe=probe, sample=sample)
problem = FitProblem(M)

**Comment by pkienzle** [comment]
Yes, I was not properly handling the to_dict() for materials and fractions.  Thanks for the report.

This is fixed now in the git repo and will be available in the next release.

I modified your example script so that it didn't require a data file to run:
```python
probe = NeutronProbe(T=np.linspace(0, 5, 100), L=4.5, dT=0.005, dL=0.045)
...
problem.to_dict()
```
