### ISSUE TITLE
feature request: checkpointing

### ISSUE THREAD

**Issue by hoogerheide** [reflectometry/refl1d#88]
It would be useful to allow checkpointing, in which data files are generated and saved to the output directory at a regular interval. This would allow convenient meta-analysis while the fit is running, and allow resuming if errors are generated well into a fit. Whether this is done by time or number of steps could be discussed, but either is reasonable (time would be more natural, I think).

**Comment by pkienzle** [comment]
Just enough state for resume? Or the complete set of plots as well?

Note that there is some information lost on resume at the moment (see bumps/bumps#29).

**Comment by hoogerheide** [comment]
The plots are useful, but possibly too dependent on having an available display? But if this isn’t an issue, I would recommend generating the plots too. I think the slowest step is writing out the -chain.mc file.

**Comment by pkienzle** [comment]
Transferring this issue to bumps repo (see bumps/bumps#30).
