### ISSUE TITLE
Remove numpy pinning for Windows build when fix is generally available

### ISSUE THREAD

**Issue by bmaranville** [reflectometry/refl1d#98]
An error in the implementation of fmod() on build 2004 of Windows 10 requires pinning numpy to version 1.19.3 until WIndows fixes are pushed out to a very large fraction of user base, or until numpy inserts their own hack to work around the problem.

See https://developercommunity.visualstudio.com/comments/1242128/view.html 

Remember to remove the pinning someday!  Relevant change is in 447bf1a9340bbb702fbb448742a23f9892f8aca7

**Comment by andyfaff** [comment]
Is `fmod` actually used in refl1d though?

**Comment by bmaranville** [comment]
can't import numpy because of the bug... I don't know how to work around that.  Can you partially import numpy?  "import numpy" fails and triggers the bug.
________________________________

**Comment by andyfaff** [comment]
Ah, I didn't know that bug prevented numpy import.

**Comment by bmaranville** [comment]
From later comments in the link above, this has a workaround from numpy >= 1.19.5
